server:
  port: 8080

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://database-1.cluster-cdc2wmaq4olp.us-west-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: root1234
    driverClassName: org.postgresql.Driver